# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: debug
  logs:
    custom_components.integration_blueprint: debug

resources:
  - url: /hacsfiles/apexcharts-card/apexcharts-card.js
    type: module

type: custom:apexcharts-card
header:
  title: "NSW1 RRP"
graph_span: 24h
span:
  start: day
series:
  - entity: sensor.nsw1_rrp_actual
    name: "RRP Actual"
    type: line
    show:
      datalabels: false
    data_generator: >
      return entity.attributes.series.map(a => {
        return { x: new Date(a[0]), y: a[1] };
      });
  - entity: sensor.nsw1_rrp_forecast
    name: "RRP Forecast"
    type: line
    show:
      datalabels: false
    data_generator: >
      return entity.attributes.series.map(a => {
        return { x: new Date(a[0]), y: a[1] };
      });